version: "3.8"

services:
  db:
    build: .docker/postgres
    container_name: restapi-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=docker12674
      - POSTGRES_DB=restapi
